# Default Values
substitutions:
  _SERVICE_NAME: hello-cloudrun 
  _REGION: asia-northeast3

steps:

### Build
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloocus-repo/${_SERVICE_NAME}", "labs/cloudrun-progression"]

### Push
  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloocus-repo/${_SERVICE_NAME}"]

### Deploy
  - id: "deploy prod service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: 
      - '-c'
      - |
          gcloud run deploy ${_SERVICE_NAME} \
            --platform managed \
            --region ${_REGION} \
            --image asia-northeast3-docker.pkg.dev/${PROJECT_ID}/cloocus-repo/${_SERVICE_NAME} \
            --tag=${BRANCH_NAME}

